Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/certbot/main.py", line 872, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 183, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/local/lib/python2.7/site-packages/certbot/plugins/disco.py", line 34, in __init__
    self.plugin_cls = entry_point.load()
  File "/Users/cc/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 2302, in load
    self.require(*args, **kwargs)
  File "/Users/cc/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 2325, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/Users/cc/Library/Python/2.7/lib/python/site-packages/pkg_resources/__init__.py", line 860, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (requests 2.9.1 (/Users/cc/Library/Python/2.7/lib/python/site-packages), Requirement.parse('requests[security]>=2.10'), set(['acme']))
